### ISSUE TITLE
Auto rotate

### ISSUE THREAD

**Issue by BLVCK-ANGEL** [Ashanime/Ashanime-Web-App#20]
could you solve the auto rotate ..

**Comment by K3NOXOFFICIAL** [comment]
Added to **#Bug Fix** at [To-Do](https://github.com/Ashanime/Ashanime-Web-App/issues/9)
Will try to Fix it on Time.

**Comment by K3NOXOFFICIAL** [comment]
What exactly is the Problem with auto Rotate?

**Comment by BLVCK-ANGEL** [comment]
its auto rotate in main page when we watch in lying on bed.
so can you make that potrait lock in mobile devices..

**Comment by K3NOXOFFICIAL** [comment]
@BLVCK-ANGEL 
Auto rotate is a feature managed by your Phone.

**To disable auto rotate on an Android device:**

1. Go to the Settings app.

1. Scroll down and tap on Display.

1. Tap on Auto-rotate screen.

1. Toggle the switch to the off position.

</br>

**To disable auto rotate on an iOS device:**

1. Go to the Settings app.

1. Tap on Display & Brightness.

1. Tap on the lock icon next to Portrait Orientation Lock.

1. Enter your passcode to unlock the setting.

1. Toggle the switch to the off position.


</br> </br>

**If you have further problems with disabling auto rotate on your device, there are a few things you can try:**

- Make sure that your device is updated to the latest version of the operating system. Sometimes issues can be fixed with software updates.

- Check for any software or app updates that may be available. Sometimes app updates can fix issues or conflicts that may be causing problems.

- Restart your device. Sometimes simply restarting your device can resolve issues.

- Check for any visible damage to your device or its components, such as the screen or sensors. If you notice any damage, it could be causing problems with the auto rotate feature.

**If none of these steps help, you may need to consult your device's documentation or contact the manufacturer or a technical support service for further assistance.**

**If you have further problems join our [discord](https://discord.gg/vDkbHKsRZM) to solve the problems.**
