### ISSUE TITLE
I check your website is not streaming anime properly

### ISSUE THREAD

**Issue by adgsenpai** [Ashanime/Ashanime-Web-App#26]
The CORS problem messes everything up. Investigate using a Cloudflare reverse proxy. Your may check my reverse proxy out and implement it for free. 

https://github.com/adgsenpai/CORSCloudFlareReverseProxy

I also wrote a paper on it 
https://zenodo.org/record/7723361#.ZA3jUnZBy3C

Best Regards
Mr Ashlin Darius Govindasamy

anime.adgstudios.co.za

**Comment by ahmedalashhab** [comment]
@adgsenpai Thank you so much for offering your proxy server to help! Much appreciated! I may use it if the current one fails. Try my app again, as I just recently implemented a proxy. Do note however that the proxy has been implemented to my live app (https://Ashanime.pro) and not this repo. I will add a guide to how to add a proxy soon so that others may replicate.

**Comment by saibendalam** [comment]
Hey Can I have the guide on implementation of proxy, I tried one on my own it works only for some links

**Comment by adgsenpai** [comment]
@saibendalam 

Try using my proxy but don't abuse it otherwise i have to pay a premium! 

https://reverseproxy.adgstudios.co.za/?url=https://google.co.za
